# command to define language
language: python
python:
  - 3.5

# command to install dependencies and modules
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

# command to run tests
script:
  - nosetests
  - coverage run setup.py test

# command to add coveralls
after_success:
  - coveralls
