# command to define language
language: python
python:
  - 3.5

# command to install dependencies and modules
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install pytest
  - python setup.py install

# command to run tests
script:
  - nosetests
  # - py.test #--cov=timeseries
  - py.test --cov=path/to/package --cov-report=term --cov-report=html

# command to add coveralls
after_success:
  - coveralls
